ZBUG-3204: added soap automation for zimbraFileUploadMaxSize
Zimbra/zm-soap-harness pull request #177
Opened 2023-05-23 11:49 UTC by vishnukantjangid

2023-05-24 07:44 UTC, pallavikhairnar21 requested changes
Hi Vishnu,
- Please move test case to briefcase and instead of bug name use file name as per test case objective.
- We can move test case GetServerRequest1 and GetServerRequest2 to Briefcase_UploadFile_Bug3204_01 - setup test case
- We can move ModifyServerRequest_Bug3204_01 and RestartMailbox_Bug3204 also in setup test case 
- After renaming test case we can add bug id in the test case 
- Move ModifyServerRequest_Bug3204_02 in finally block

2023-05-24 07:49 UTC, jiteshsojitra commented
>> Briefcase_UploadFile_Bug3204_01
We don't want to keep bug number at all in file name or anywhere until test PASSES. The file name/description itself should describe what test for...

2023-05-24 12:45 UTC, vishnukantjangid commented
> Hi Vishnu,
> 
> * Please move test case to briefcase and instead of bug name use file name as per test case objective.
> * We can move test case GetServerRequest1 and GetServerRequest2 to Briefcase_UploadFile_Bug3204_01 - setup test case
> * We can move ModifyServerRequest_Bug3204_01 and RestartMailbox_Bug3204 also in setup test case
> * After renaming test case we can add bug id in the test case
> * Move ModifyServerRequest_Bug3204_02 in finally block

Done. please verify

2023-05-24 12:56 UTC, pallavikhairnar21 approved these changes

2023-05-25 13:00 UTC, prashantajari requested changes

2023-08-25 10:43 UTC, merged